site_name: CBuddhaHub
site_url: http://abc.cra2y6uddha.fun/


nav:
  - index.md
  - 个人博客:
    - blog/index.md
  - 基础与难题:
    - 序言:
      - CBuddhahub/index_basic.md
    - 基础:
      - basic/IDEA中的Maven使用方法.md
      - basic/JAVA网络编程.md
      - basic/javaWeb之请求响应.md
      - basic/Maven高级使用.md
  - 算法与数据结构:
    - 序言:
      - CBuddhahub/index_algorithm.md
    - 算法导论:
      - algorithm/1-算法导论/导出/分治策略_.md
      - algorithm/1-算法导论/导出/名词解释_.md
      - algorithm/1-算法导论/分治策略解决最大子数组的逻辑.md
    - 数据结构:
      - algorithm/2-数据结构/表、栈和队列.md
  - 数据库教程:
    - 序言:
      - CBuddhahub/index_db.md
    - 正式开始:
      - db/数据库设计与操作的重要知识点.md
      - db/mybatis教程.md
      - db/Redis教程.md
  - SpringBoot教程:
    - 序言:
      - CBuddhahub/index_springboot.md
    - 正式开始:
      - CBuddhahub_springboot/SpringBoot原理.md
      - CBuddhahub_springboot/登录校验与认证.md
      - CBuddhahub_springboot/实现springboot分层解耦技术.md
      - CBuddhahub_springboot/事务管理&AOP.md
      - CBuddhahub_springboot/spring项目术语表.md
      - CBuddhahub_springboot/springboot实战项目-寰宇外卖重难点总结.md
  - AI领域:
    - 序言:
      - CBuddhahub/index_ai.md
    - 正式开始:
      - Transformers实战篇:
        - LLM/Transformers实战篇/基于截断策略的机器阅读理解任务实现.md
        - LLM/Transformers实战篇/命名实体识别.md
      - LLM/Transformers显存优化策略.md
      - LLM/大语言模型性能对比.md
  - RE领域:
    - 序言:
      - CBuddhahub/index_ReverseEngineering.md
    - 正式开始:
      - RE/RE(1).md
      - RE/RE(2).md
      - RE/RE(3).md
      - RE/RE(4).md
  -  大数据分析与代码实现:
      - Jupyter笔记本:
        - code/demo-nb.ipynb
      - Python文件: 
        - code/notebook.py

theme:
  name: material
  custom_dir: overrides
  language: zh
  logo: assets/logo.jpg
  favicon: assets/logo.jpg
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.path
    - toc.follow
    - navigation.top
    - navigation.indexes
    - navigation.footer
  palette: 

    # Palette toggle for light mode
    - scheme: cbhub
      primary: lime  
      toggle:
        icon: material/toggle-switch 
        name: 切换到暗模式

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换到亮模式
  icon:
    repo: fontawesome/brands/chrome  
  font: false


plugins:
  - search
  - mkdocs-jupyter
  - blog:
      authors_profiles: true
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
      enabled: !ENV
      comments_path: "#__comments"
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - css/base.css
extra_javascript:
  - js/base.js
repo_url: http://www.cra2y6uddha.fun/
repo_name: 我的ai多模态网站

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/CrazyBuddha-Max
      name: CrazyBuddha-Max on github
    - icon: fontawesome/brands/gitlab
      link: http://www.cra2y6uddha.fun/
      name: 我的另一个ai多模态网站
  generator: false
  analytics:
    provider: google
    property: G-CEY7FQJJ7D
    feedback:
      title: 这个页面对你有帮助吗?
      ratings:
        - icon: material/emoticon-happy-outline
          name: 这个页面有帮助！
          data: 1
          note: >-
            谢谢你的反馈!
        - icon: material/emoticon-sad-outline
          name: 这个页面没有用!
          data: 0
          note: >- 
            感谢你的反馈! 帮助我们改进此页面，使用我们的<a href="..." target="_blank" rel="noopener">反馈表单</a>.

copyright: myweb by CrazyBuddha is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>
